# Project: day02_20180828
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 回文.o
LINKOBJ  = 回文.o
LIBS     = -L"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib" -L"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = day02_20180828.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

回文.o: 回文.c
	$(CC) -c 回文.c -o 回文.o $(CFLAGS)
