# Project: day01_20180827
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 等腰三角形.o
LINKOBJ  = 等腰三角形.o
LIBS     = -L"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib" -L"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/01developer/01app/02tool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = day01basis_20180827.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

等腰三角形.o: 等腰三角形.c
	$(CC) -c 等腰三角形.c -o 等腰三角形.o $(CFLAGS)
